// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1mcqlsKH8w5_o0ETc1AT5OVRDl4PLXcI',
    appId: '1:27869014226:web:b3b37e1ce925fa9ecc650b',
    messagingSenderId: '27869014226',
    projectId: 'ruhiy-b6756',
    authDomain: 'ruhiy-b6756.firebaseapp.com',
    storageBucket: 'ruhiy-b6756.appspot.com',
    measurementId: 'G-VTNQJRGPKD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCV4zviUUVkNyT5EFc5FsWcuR7VpsiK-w8',
    appId: '1:27869014226:android:166d7c136560df7bcc650b',
    messagingSenderId: '27869014226',
    projectId: 'ruhiy-b6756',
    storageBucket: 'ruhiy-b6756.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChgvZ2r6Pp9lqZtugMUiL9XtCP721rmzw',
    appId: '1:27869014226:ios:ebba9c1e0d77f288cc650b',
    messagingSenderId: '27869014226',
    projectId: 'ruhiy-b6756',
    storageBucket: 'ruhiy-b6756.appspot.com',
    iosClientId: '27869014226-kt0h7f48lukehc8t129c35jm1r67kefe.apps.googleusercontent.com',
    iosBundleId: 'com.example.ruhiyapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChgvZ2r6Pp9lqZtugMUiL9XtCP721rmzw',
    appId: '1:27869014226:ios:0aefb67630dd2ed0cc650b',
    messagingSenderId: '27869014226',
    projectId: 'ruhiy-b6756',
    storageBucket: 'ruhiy-b6756.appspot.com',
    iosClientId: '27869014226-clnh49a7sip3qnpai8avam6c4gfdmadq.apps.googleusercontent.com',
    iosBundleId: 'com.example.ruhiyapp.RunnerTests',
  );
}
